language: php

dist: trusty
sudo: false

stages:
  - Code Format and Static Analysis
  - Units
  - Test CommonMark (weak)

matrix:    
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAILURE

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: Code Format and Static Analysis
      php: 7.3
      install: composer install --prefer-dist --no-interaction --no-progress
      script:
        - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"vendor/autoload.php\"); echo Erusev\Parsedown\Parsedown::version;")" ]'
        - composer test-static
        - composer test-formatting
        - composer test-dead-code


    - &UNIT_TEST
      stage: Units
      php: 5.5
      install:
        # remove packages with PHP requirements higher than 7.0 to prevent composer trying to resolve these, see: https://github.com/composer/composer/issues/6011
        - composer remove vimeo/psalm friendsofphp/php-cs-fixer infection/infection --dev --no-update --no-interaction
        - composer install --prefer-dist --no-interaction --no-progress
      script: composer test-units
    - <<: *UNIT_TEST
      php: 5.6
    - <<: *UNIT_TEST
      php: 7.0
    - &MUTATION_AND_UNIT_TEST
      <<: *UNIT_TEST
      php: 7.1
      install:
        - composer install --prefer-dist --no-interaction --no-progress
      script:
        - composer test-units
        - vendor/bin/infection --show-mutations --threads=4 --min-msi=90 --min-covered-msi=90
    - <<: *MUTATION_AND_UNIT_TEST
      php: 7.2
    - <<: *MUTATION_AND_UNIT_TEST
      php: 7.3
    - <<: *UNIT_TEST
      php: nightly
      env: ALLOW_FAILURE


    - &COMMONMARK_TEST
      stage: CommonMark
      name: Weak
      php: 7.3
      env: ALLOW_FAILURE
      install: composer install --prefer-dist --no-interaction --no-progress
      script:
        - composer test-commonmark-weak

    - <<: *COMMONMARK_TEST
      name: Strict
      script:
        - composer test-commonmark
